version: '3.9'

services:
  frontend:
    build: .
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
