version: '3.9'

services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "cfcollab.wsgi:application"]
