name: CI for Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./Sergi/frontend
        run: |
          npm ci

      - name: Run Lint
        working-directory: ./Sergi/frontend
        run: |
          npm run lint

      - name: Run Tests
        working-directory: ./Sergi/frontend
        run: |
          npm test -- --watchAll=false

      - name: Build Frontend
        working-directory: ./Sergi/frontend
        run: |
          npm run build

  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: ./Sergi/backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        working-directory: ./Sergi/backend
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run Lint
        working-directory: ./Sergi/backend
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run Tests
        working-directory: ./Sergi/backend
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
        run: |
          source venv/bin/activate
          python manage.py test
